# Generated by Django 4.1.2 on 2022-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an Exception Type.', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dex',
            name='exception',
            field=models.ManyToManyField(help_text='Select an Exception.', to='operationsMetrics.exceptions'),
        ),
    ]
