# Generated by Django 4.1.2 on 2022-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='DEX', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='packagesPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Packages Per Hour', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='volumeAvailabilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Volume Availability Status', max_length=200)),
            ],
        ),
    ]
