# Generated by Django 4.1.2 on 2022-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0004_facility_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='region',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='region',
            name='summary',
        ),
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.CharField(default='noAddress', help_text='Enter a Facility Location.', max_length=20, unique=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text='Enter a Facility Name.', max_length=200),
        ),
    ]
