# Generated by Django 4.1.2 on 2022-11-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0005_alter_region_options_rename_title_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='facility',
            field=models.ManyToManyField(help_text='Select a Facility to add to the Region.', to='operationsMetrics.facility'),
        ),
    ]
