# Generated by Django 4.1.2 on 2022-11-03 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0006_alter_region_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagesperhour',
            options={'ordering': ['-pph']},
        ),
        migrations.AddField(
            model_name='packagesperhour',
            name='pph',
            field=models.IntegerField(default=0, help_text='Enter the Number of Packages per Hour', verbose_name='packagesPerHour'),
        ),
        migrations.AddField(
            model_name='packagesperhour',
            name='pphDate',
            field=models.DateField(default=datetime.date.today, help_text='Enter the Date for the Data', verbose_name='Date'),
        ),
    ]
