# Generated by Django 4.1.2 on 2022-11-03 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0007_alter_packagesperhour_options_packagesperhour_pph_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagesperhour',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='packagesperhour',
            name='name',
        ),
        migrations.RemoveField(
            model_name='packagesperhour',
            name='pphDate',
        ),
        migrations.AddField(
            model_name='packagesperhour',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='packagesperhour',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operationsMetrics.facility'),
        ),
    ]
