# Generated by Django 4.1.2 on 2022-11-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0008_alter_packagesperhour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesperhour',
            name='facility',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='operationsMetrics.facility'),
        ),
    ]
