# Generated by Django 4.1.2 on 2022-11-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0015_alter_packagesperhour_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesperhour',
            name='facility',
        ),
    ]
