# Generated by Django 4.1.2 on 2022-11-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0016_remove_packagesperhour_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(blank=True, default='noAddress', help_text='Enter a Facility Location.', max_length=20, null=True, unique=True, verbose_name='Location'),
        ),
    ]
