# Generated by Django 4.1.2 on 2022-11-03 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0018_alter_facility_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesperhour',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='packagesperhour',
            name='pph',
            field=models.IntegerField(blank=True, default=0, help_text='Enter the Number of Packages per Hour', null=True, verbose_name='packagesPerHour'),
        ),
    ]
