# Generated by Django 4.1.2 on 2022-11-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0019_alter_packagesperhour_date_alter_packagesperhour_pph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagesperhour',
            options={},
        ),
    ]
