# Generated by Django 4.1.2 on 2022-11-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0020_alter_packagesperhour_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(default='noAddress', help_text='Enter a Facility Location.', max_length=20, verbose_name='Location'),
        ),
    ]
