# Generated by Django 4.1.2 on 2022-11-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0021_alter_facility_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagesperhour',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='packagesperhour',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operationsMetrics.facility'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(default='noAddress', help_text='Enter a Facility Location.', max_length=20, unique=True, verbose_name='Location'),
        ),
    ]
