# Generated by Django 4.1.2 on 2022-11-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0022_alter_packagesperhour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesperhour',
            name='facility',
            field=models.ForeignKey(blank=True, default='test', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operationsMetrics.facility'),
        ),
    ]
