# Generated by Django 4.1.2 on 2022-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationsMetrics', '0023_alter_packagesperhour_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagesperhour',
            options={'ordering': ['pph']},
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text='Enter a Facility Name.', max_length=100),
        ),
    ]
