# Generated by Django 4.1.2 on 2022-12-06 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter District Name.', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Division Name', max_length=10)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opMetrics.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['lastName'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Location Name.', max_length=5)),
                ('senior_Manager', models.CharField(help_text='Enter the Location Type.', max_length=25)),
                ('type', models.CharField(choices=[('Hub', 'Hub'), ('Ramp', 'Ramp'), ('Station', 'Station')], default='Hub', max_length=10)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona       '), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado      '), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida       '), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho         '), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa          '), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana     '), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts '), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi   '), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska      '), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey    '), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('OR', 'North Dakota'), ('PA', 'Ohio'), ('RI', 'Oklahoma      '), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island  '), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee     '), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont       '), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia '), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='AL', max_length=2)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opMetrics.district')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Region Name', max_length=15)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opMetrics.division')),
            ],
        ),
        migrations.CreateModel(
            name='packagesPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pph', models.IntegerField(blank=True, default=0, help_text='Enter the Number of Packages per Hour', null=True, verbose_name='packagesPerHour')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opMetrics.location')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('address1', models.CharField(max_length=128, verbose_name='address')),
                ('address2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Zanesville', max_length=64, verbose_name='city')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona       '), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado      '), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida       '), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho         '), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa          '), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana     '), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts '), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi   '), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska      '), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey    '), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('OR', 'North Dakota'), ('PA', 'Ohio'), ('RI', 'Oklahoma      '), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island  '), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee     '), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont       '), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia '), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='AL', max_length=2)),
                ('zip_code', models.CharField(default='43701', max_length=5, verbose_name='zip code')),
                ('dateTime', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opMetrics.location')),
            ],
            options={
                'ordering': ['dateTime'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='opMetrics.region'),
        ),
    ]
