# Generated by Django 4.1.2 on 2022-12-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opMetrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='last_name',
        ),
    ]
