# Generated by Django 4.1.2 on 2022-12-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opMetrics', '0002_remove_package_first_name_remove_package_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='first_name',
            field=models.CharField(default='no', max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='last_name',
            field=models.CharField(default='no', max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
