# Generated by Django 4.1.2 on 2022-12-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opMetrics', '0003_package_first_name_package_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packagesperhour',
            name='location',
            field=models.ForeignKey(default=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='opMetrics.location'),
        ),
    ]
