# Generated by Django 4.1.2 on 2022-12-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opMetrics', '0004_alter_location_id_alter_packagesperhour_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
