# Generated by Django 4.1.2 on 2022-12-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opMetrics', '0005_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesperhour',
            name='location',
            field=models.CharField(default='delete', max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
    ]
