# Generated by Django 4.1.2 on 2022-12-08 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opMetrics', '0006_alter_packagesperhour_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesperhour',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opMetrics.location'),
        ),
    ]
